import Chain from '../types/chain';
import { ConstRecord } from '../types/const';
export * from '../types/chainid';
declare const _addressBook: {
    readonly avax: Chain;
    readonly fantom: Chain;
    readonly one: Chain;
    readonly metis: Chain;
    readonly moonbeam: Chain;
    readonly sys: Chain;
    readonly celo: Chain;
    readonly aurora: Chain;
    readonly moonriver: Chain;
    readonly fuse: Chain;
    readonly bsc: Chain;
    readonly polygon: Chain;
    readonly cronos: Chain;
    readonly heco: Chain;
    readonly arbitrum: Chain;
    readonly emerald: Chain;
    readonly telos: Chain;
};
declare const _addressBookByChainId: {
    readonly '56': Chain;
    readonly '43114': Chain;
    readonly '25': Chain;
    readonly '42220': Chain;
    readonly '1088': Chain;
    readonly '1285': Chain;
    readonly '1284': Chain;
    readonly '250': Chain;
    readonly '1666600000': Chain;
    readonly '122': Chain;
    readonly '137': Chain;
    readonly '128': Chain;
    readonly '1313161554': Chain;
    readonly '42161': Chain;
    readonly '57': Chain;
    readonly '42262': Chain;
    readonly '40': Chain;
};
export declare const addressBook: ConstRecord<typeof _addressBook, Chain>;
export declare const addressBookByChainId: ConstRecord<typeof _addressBookByChainId, Chain>;
